2020-04-17 19:14:27 [scrapy.extensions.telnet] INFO: Telnet Password: 5d07b3d9abe99466
2020-04-17 19:14:27 [scrapy.middleware] INFO: Enabled extensions:
['scrapy.extensions.corestats.CoreStats',
 'scrapy.extensions.telnet.TelnetConsole',
 'scrapy.extensions.logstats.LogStats']
2020-04-17 19:14:28 [scrapy.middleware] INFO: Enabled downloader middlewares:
['ziroom.middlewares.ProxyMiddleware',
 'scrapy.downloadermiddlewares.robotstxt.RobotsTxtMiddleware',
 'scrapy.downloadermiddlewares.httpauth.HttpAuthMiddleware',
 'scrapy.downloadermiddlewares.downloadtimeout.DownloadTimeoutMiddleware',
 'scrapy.downloadermiddlewares.defaultheaders.DefaultHeadersMiddleware',
 'scrapy.downloadermiddlewares.useragent.UserAgentMiddleware',
 'scrapy.downloadermiddlewares.retry.RetryMiddleware',
 'scrapy.downloadermiddlewares.redirect.MetaRefreshMiddleware',
 'scrapy.downloadermiddlewares.httpcompression.HttpCompressionMiddleware',
 'scrapy.downloadermiddlewares.redirect.RedirectMiddleware',
 'scrapy.downloadermiddlewares.cookies.CookiesMiddleware',
 'scrapy.downloadermiddlewares.httpproxy.HttpProxyMiddleware',
 'scrapy.downloadermiddlewares.stats.DownloaderStats']
2020-04-17 19:14:28 [scrapy.middleware] INFO: Enabled spider middlewares:
['scrapy.spidermiddlewares.httperror.HttpErrorMiddleware',
 'scrapy.spidermiddlewares.offsite.OffsiteMiddleware',
 'scrapy.spidermiddlewares.referer.RefererMiddleware',
 'scrapy.spidermiddlewares.urllength.UrlLengthMiddleware',
 'scrapy.spidermiddlewares.depth.DepthMiddleware']
2020-04-17 19:14:28 [scrapy.middleware] INFO: Enabled item pipelines:
['ziroom.pipelines.ZiroomPipeline', 'ziroom.pipelines.ZiroomPipelineJson']
2020-04-17 19:14:28 [scrapy.core.engine] INFO: Spider opened
2020-04-17 19:14:28 [scrapy.extensions.logstats] INFO: Crawled 0 pages (at 0 pages/min), scraped 0 items (at 0 items/min)
2020-04-17 19:14:28 [scrapy.extensions.telnet] INFO: Telnet console listening on 127.0.0.1:6023
2020-04-17 19:14:28 [urllib3.connectionpool] DEBUG: Starting new HTTPS connection (1): www.xicidaili.com:443
2020-04-17 19:14:28 [urllib3.connectionpool] DEBUG: https://www.xicidaili.com:443 "GET /nn/ HTTP/1.1" 200 None
2020-04-17 19:14:28 [urllib3.connectionpool] DEBUG: Starting new HTTPS connection (1): www.baidu.com:443
2020-04-17 19:14:28 [urllib3.connectionpool] DEBUG: https://www.baidu.com:443 "GET / HTTP/1.1" 200 None
2020-04-17 19:14:28 [urllib3.connectionpool] DEBUG: Starting new HTTPS connection (1): www.baidu.com:443
2020-04-17 19:14:28 [urllib3.connectionpool] DEBUG: https://www.baidu.com:443 "GET / HTTP/1.1" 200 None
2020-04-17 19:14:28 [urllib3.connectionpool] DEBUG: Starting new HTTPS connection (1): www.baidu.com:443
2020-04-17 19:14:28 [urllib3.connectionpool] DEBUG: https://www.baidu.com:443 "GET / HTTP/1.1" 200 None
2020-04-17 19:14:28 [urllib3.connectionpool] DEBUG: Starting new HTTPS connection (1): www.baidu.com:443
2020-04-17 19:14:28 [urllib3.connectionpool] DEBUG: https://www.baidu.com:443 "GET / HTTP/1.1" 200 None
2020-04-17 19:14:28 [urllib3.connectionpool] DEBUG: Starting new HTTPS connection (1): www.baidu.com:443
2020-04-17 19:14:28 [urllib3.connectionpool] DEBUG: https://www.baidu.com:443 "GET / HTTP/1.1" 200 None
2020-04-17 19:14:28 [urllib3.connectionpool] DEBUG: Starting new HTTPS connection (1): www.baidu.com:443
2020-04-17 19:14:28 [urllib3.connectionpool] DEBUG: https://www.baidu.com:443 "GET / HTTP/1.1" 200 None
2020-04-17 19:14:28 [urllib3.connectionpool] DEBUG: Starting new HTTPS connection (1): www.baidu.com:443
2020-04-17 19:14:28 [urllib3.connectionpool] DEBUG: https://www.baidu.com:443 "GET / HTTP/1.1" 200 None
2020-04-17 19:14:28 [urllib3.connectionpool] DEBUG: Starting new HTTPS connection (1): www.baidu.com:443
2020-04-17 19:14:28 [urllib3.connectionpool] DEBUG: https://www.baidu.com:443 "GET / HTTP/1.1" 200 None
2020-04-17 19:14:28 [urllib3.connectionpool] DEBUG: Starting new HTTPS connection (1): www.baidu.com:443
2020-04-17 19:14:28 [urllib3.connectionpool] DEBUG: https://www.baidu.com:443 "GET / HTTP/1.1" 200 None
2020-04-17 19:14:28 [urllib3.connectionpool] DEBUG: Starting new HTTPS connection (1): www.xicidaili.com:443
2020-04-17 19:14:28 [urllib3.connectionpool] DEBUG: https://www.xicidaili.com:443 "GET /nn/ HTTP/1.1" 200 None
2020-04-17 19:14:28 [urllib3.connectionpool] DEBUG: Starting new HTTPS connection (1): www.baidu.com:443
2020-04-17 19:14:28 [urllib3.connectionpool] DEBUG: https://www.baidu.com:443 "GET / HTTP/1.1" 200 None
2020-04-17 19:14:28 [urllib3.connectionpool] DEBUG: Starting new HTTPS connection (1): www.baidu.com:443
2020-04-17 19:14:28 [urllib3.connectionpool] DEBUG: https://www.baidu.com:443 "GET / HTTP/1.1" 200 None
2020-04-17 19:14:28 [urllib3.connectionpool] DEBUG: Starting new HTTPS connection (1): www.baidu.com:443
2020-04-17 19:14:28 [urllib3.connectionpool] DEBUG: https://www.baidu.com:443 "GET / HTTP/1.1" 200 None
2020-04-17 19:14:28 [urllib3.connectionpool] DEBUG: Starting new HTTPS connection (1): www.baidu.com:443
2020-04-17 19:14:28 [urllib3.connectionpool] DEBUG: https://www.baidu.com:443 "GET / HTTP/1.1" 200 None
2020-04-17 19:14:28 [urllib3.connectionpool] DEBUG: Starting new HTTPS connection (1): www.baidu.com:443
2020-04-17 19:14:28 [urllib3.connectionpool] DEBUG: https://www.baidu.com:443 "GET / HTTP/1.1" 200 None
2020-04-17 19:14:29 [urllib3.connectionpool] DEBUG: Starting new HTTPS connection (1): www.baidu.com:443
2020-04-17 19:14:29 [urllib3.connectionpool] DEBUG: https://www.baidu.com:443 "GET / HTTP/1.1" 200 None
2020-04-17 19:14:29 [urllib3.connectionpool] DEBUG: Starting new HTTPS connection (1): www.baidu.com:443
2020-04-17 19:14:29 [urllib3.connectionpool] DEBUG: https://www.baidu.com:443 "GET / HTTP/1.1" 200 None
2020-04-17 19:14:29 [urllib3.connectionpool] DEBUG: Starting new HTTPS connection (1): www.baidu.com:443
2020-04-17 19:14:29 [urllib3.connectionpool] DEBUG: https://www.baidu.com:443 "GET / HTTP/1.1" 200 None
2020-04-17 19:14:29 [urllib3.connectionpool] DEBUG: Starting new HTTPS connection (1): www.baidu.com:443
2020-04-17 19:14:29 [urllib3.connectionpool] DEBUG: https://www.baidu.com:443 "GET / HTTP/1.1" 200 None
2020-04-17 19:14:30 [scrapy.core.engine] DEBUG: Crawled (200) <GET http://www.ziroom.com/robots.txt> (referer: None)
2020-04-17 19:14:32 [scrapy.downloadermiddlewares.retry] DEBUG: Retrying <GET http://www.ziroom.com/z/s100001-p1/> (failed 1 times): Connection was refused by other side: 10061: 由于目标计算机积极拒绝，无法连接。.
2020-04-17 19:14:32 [urllib3.connectionpool] DEBUG: Starting new HTTPS connection (1): www.xicidaili.com:443
2020-04-17 19:14:32 [urllib3.connectionpool] DEBUG: https://www.xicidaili.com:443 "GET /nn/ HTTP/1.1" 200 None
2020-04-17 19:14:32 [urllib3.connectionpool] DEBUG: Starting new HTTPS connection (1): www.baidu.com:443
2020-04-17 19:14:32 [urllib3.connectionpool] DEBUG: https://www.baidu.com:443 "GET / HTTP/1.1" 200 None
2020-04-17 19:14:32 [urllib3.connectionpool] DEBUG: Starting new HTTPS connection (1): www.baidu.com:443
2020-04-17 19:14:32 [urllib3.connectionpool] DEBUG: https://www.baidu.com:443 "GET / HTTP/1.1" 200 None
2020-04-17 19:14:32 [urllib3.connectionpool] DEBUG: Starting new HTTPS connection (1): www.baidu.com:443
2020-04-17 19:14:32 [urllib3.connectionpool] DEBUG: https://www.baidu.com:443 "GET / HTTP/1.1" 200 None
2020-04-17 19:14:32 [urllib3.connectionpool] DEBUG: Starting new HTTPS connection (1): www.baidu.com:443
2020-04-17 19:14:32 [urllib3.connectionpool] DEBUG: https://www.baidu.com:443 "GET / HTTP/1.1" 200 None
2020-04-17 19:14:32 [urllib3.connectionpool] DEBUG: Starting new HTTPS connection (1): www.baidu.com:443
2020-04-17 19:14:32 [urllib3.connectionpool] DEBUG: https://www.baidu.com:443 "GET / HTTP/1.1" 200 None
2020-04-17 19:14:32 [urllib3.connectionpool] DEBUG: Starting new HTTPS connection (1): www.baidu.com:443
2020-04-17 19:14:32 [urllib3.connectionpool] DEBUG: https://www.baidu.com:443 "GET / HTTP/1.1" 200 None
2020-04-17 19:14:32 [urllib3.connectionpool] DEBUG: Starting new HTTPS connection (1): www.baidu.com:443
2020-04-17 19:14:32 [urllib3.connectionpool] DEBUG: https://www.baidu.com:443 "GET / HTTP/1.1" 200 None
2020-04-17 19:14:32 [urllib3.connectionpool] DEBUG: Starting new HTTPS connection (1): www.baidu.com:443
2020-04-17 19:14:32 [urllib3.connectionpool] DEBUG: https://www.baidu.com:443 "GET / HTTP/1.1" 200 None
2020-04-17 19:14:32 [urllib3.connectionpool] DEBUG: Starting new HTTPS connection (1): www.baidu.com:443
2020-04-17 19:14:32 [urllib3.connectionpool] DEBUG: https://www.baidu.com:443 "GET / HTTP/1.1" 200 None
2020-04-17 19:14:35 [scrapy.downloadermiddlewares.retry] DEBUG: Retrying <GET http://www.ziroom.com/z/s100001-p1/> (failed 2 times): Connection was refused by other side: 10061: 由于目标计算机积极拒绝，无法连接。.
2020-04-17 19:14:35 [urllib3.connectionpool] DEBUG: Starting new HTTPS connection (1): www.xicidaili.com:443
2020-04-17 19:14:35 [urllib3.connectionpool] DEBUG: https://www.xicidaili.com:443 "GET /nn/ HTTP/1.1" 200 None
2020-04-17 19:14:35 [urllib3.connectionpool] DEBUG: Starting new HTTPS connection (1): www.baidu.com:443
2020-04-17 19:14:35 [urllib3.connectionpool] DEBUG: https://www.baidu.com:443 "GET / HTTP/1.1" 200 None
2020-04-17 19:14:35 [urllib3.connectionpool] DEBUG: Starting new HTTPS connection (1): www.baidu.com:443
2020-04-17 19:14:35 [urllib3.connectionpool] DEBUG: https://www.baidu.com:443 "GET / HTTP/1.1" 200 None
2020-04-17 19:14:35 [urllib3.connectionpool] DEBUG: Starting new HTTPS connection (1): www.baidu.com:443
2020-04-17 19:14:35 [urllib3.connectionpool] DEBUG: https://www.baidu.com:443 "GET / HTTP/1.1" 200 None
2020-04-17 19:14:35 [urllib3.connectionpool] DEBUG: Starting new HTTPS connection (1): www.baidu.com:443
2020-04-17 19:14:35 [urllib3.connectionpool] DEBUG: https://www.baidu.com:443 "GET / HTTP/1.1" 200 None
2020-04-17 19:14:35 [urllib3.connectionpool] DEBUG: Starting new HTTPS connection (1): www.baidu.com:443
2020-04-17 19:14:35 [urllib3.connectionpool] DEBUG: https://www.baidu.com:443 "GET / HTTP/1.1" 200 None
2020-04-17 19:14:35 [urllib3.connectionpool] DEBUG: Starting new HTTPS connection (1): www.baidu.com:443
2020-04-17 19:14:35 [urllib3.connectionpool] DEBUG: https://www.baidu.com:443 "GET / HTTP/1.1" 200 None
2020-04-17 19:14:35 [urllib3.connectionpool] DEBUG: Starting new HTTPS connection (1): www.baidu.com:443
2020-04-17 19:14:35 [urllib3.connectionpool] DEBUG: https://www.baidu.com:443 "GET / HTTP/1.1" 200 None
2020-04-17 19:14:35 [urllib3.connectionpool] DEBUG: Starting new HTTPS connection (1): www.baidu.com:443
2020-04-17 19:14:35 [urllib3.connectionpool] DEBUG: https://www.baidu.com:443 "GET / HTTP/1.1" 200 None
2020-04-17 19:14:35 [urllib3.connectionpool] DEBUG: Starting new HTTPS connection (1): www.baidu.com:443
2020-04-17 19:14:35 [urllib3.connectionpool] DEBUG: https://www.baidu.com:443 "GET / HTTP/1.1" 200 None
2020-04-17 19:14:38 [scrapy.core.engine] DEBUG: Crawled (200) <GET http://www.ziroom.com/z/s100001-p1/> (referer: None) ['partial']
2020-04-17 19:14:38 [py.warnings] WARNING: C:\Users\rench\AppData\Local\Programs\Python\Python37\lib\site-packages\scrapy\core\scraper.py:148: UserWarning: The "ZiroomSpider.parse" method is a generator and includes a "return" statement with a value different than None. This could lead to unexpected behaviour. Please see https://docs.python.org/3/reference/simple_stmts.html#the-return-statement for details about the semantics of the "return" statement within generators
  warn_on_generator_with_return_value(spider, callback)

2020-04-17 19:14:38 [urllib3.connectionpool] DEBUG: Starting new HTTP connection (1): static8.ziroom.com:80
2020-04-17 19:14:38 [urllib3.connectionpool] DEBUG: http://static8.ziroom.com:80 "GET /phoenix/pc/images/price/new-list/377327c0373f87395ab1908cd1607c1b.png HTTP/1.1" 200 3510
2020-04-17 19:14:38 [PIL.PngImagePlugin] DEBUG: STREAM b'IHDR' 16 13
2020-04-17 19:14:38 [PIL.PngImagePlugin] DEBUG: STREAM b'IDAT' 41 3453
2020-04-17 19:14:41 [urllib3.connectionpool] DEBUG: Starting new HTTPS connection (1): aip.baidubce.com:443
2020-04-17 19:14:41 [urllib3.connectionpool] DEBUG: https://aip.baidubce.com:443 "GET /oauth/2.0/token?grant_type=client_credentials&client_id=yVlspwRqI1giqXTGX051hofL&client_secret=ZChUT1fZLWdRpVyGoMwwA492TqViYEnG HTTP/1.1" 200 None
2020-04-17 19:14:41 [urllib3.connectionpool] DEBUG: Starting new HTTPS connection (1): aip.baidubce.com:443
2020-04-17 19:14:42 [urllib3.connectionpool] DEBUG: https://aip.baidubce.com:443 "POST /rest/2.0/ocr/v1/general_basic?access_token=24.e97f3cd231bd37ec01f255e525582a21.2592000.1589714081.282335-19383742&aipSdk=python&aipVersion=2_2_18 HTTP/1.1" 200 96
2020-04-17 19:14:42 [scrapy.core.scraper] DEBUG: Scraped from <200 http://www.ziroom.com/z/s100001-p1/>
None
2020-04-17 19:14:42 [urllib3.connectionpool] DEBUG: Starting new HTTP connection (1): static8.ziroom.com:80
2020-04-17 19:14:42 [urllib3.connectionpool] DEBUG: http://static8.ziroom.com:80 "GET /phoenix/pc/images/price/new-list/377327c0373f87395ab1908cd1607c1b.png HTTP/1.1" 200 3510
2020-04-17 19:14:42 [PIL.PngImagePlugin] DEBUG: STREAM b'IHDR' 16 13
2020-04-17 19:14:42 [PIL.PngImagePlugin] DEBUG: STREAM b'IDAT' 41 3453
2020-04-17 19:14:45 [urllib3.connectionpool] DEBUG: Starting new HTTPS connection (1): aip.baidubce.com:443
2020-04-17 19:14:45 [urllib3.connectionpool] DEBUG: https://aip.baidubce.com:443 "POST /rest/2.0/ocr/v1/general_basic?access_token=24.e97f3cd231bd37ec01f255e525582a21.2592000.1589714081.282335-19383742&aipSdk=python&aipVersion=2_2_18 HTTP/1.1" 200 94
2020-04-17 19:14:45 [scrapy.core.scraper] DEBUG: Scraped from <200 http://www.ziroom.com/z/s100001-p1/>
None
2020-04-17 19:14:45 [urllib3.connectionpool] DEBUG: Starting new HTTP connection (1): static8.ziroom.com:80
2020-04-17 19:14:45 [urllib3.connectionpool] DEBUG: http://static8.ziroom.com:80 "GET /phoenix/pc/images/price/new-list/377327c0373f87395ab1908cd1607c1b.png HTTP/1.1" 200 3510
2020-04-17 19:14:45 [PIL.PngImagePlugin] DEBUG: STREAM b'IHDR' 16 13
2020-04-17 19:14:45 [PIL.PngImagePlugin] DEBUG: STREAM b'IDAT' 41 3453
2020-04-17 19:14:48 [urllib3.connectionpool] DEBUG: Starting new HTTPS connection (1): aip.baidubce.com:443
2020-04-17 19:14:48 [urllib3.connectionpool] DEBUG: https://aip.baidubce.com:443 "POST /rest/2.0/ocr/v1/general_basic?access_token=24.e97f3cd231bd37ec01f255e525582a21.2592000.1589714081.282335-19383742&aipSdk=python&aipVersion=2_2_18 HTTP/1.1" 200 96
2020-04-17 19:14:48 [scrapy.core.scraper] DEBUG: Scraped from <200 http://www.ziroom.com/z/s100001-p1/>
None
2020-04-17 19:14:48 [urllib3.connectionpool] DEBUG: Starting new HTTP connection (1): static8.ziroom.com:80
2020-04-17 19:14:48 [urllib3.connectionpool] DEBUG: http://static8.ziroom.com:80 "GET /phoenix/pc/images/price/new-list/377327c0373f87395ab1908cd1607c1b.png HTTP/1.1" 200 3510
2020-04-17 19:14:48 [PIL.PngImagePlugin] DEBUG: STREAM b'IHDR' 16 13
2020-04-17 19:14:48 [PIL.PngImagePlugin] DEBUG: STREAM b'IDAT' 41 3453
2020-04-17 19:14:51 [urllib3.connectionpool] DEBUG: Starting new HTTPS connection (1): aip.baidubce.com:443
2020-04-17 19:14:51 [urllib3.connectionpool] DEBUG: https://aip.baidubce.com:443 "POST /rest/2.0/ocr/v1/general_basic?access_token=24.e97f3cd231bd37ec01f255e525582a21.2592000.1589714081.282335-19383742&aipSdk=python&aipVersion=2_2_18 HTTP/1.1" 200 95
2020-04-17 19:14:51 [scrapy.core.scraper] DEBUG: Scraped from <200 http://www.ziroom.com/z/s100001-p1/>
None
2020-04-17 19:14:51 [urllib3.connectionpool] DEBUG: Starting new HTTP connection (1): static8.ziroom.com:80
2020-04-17 19:14:51 [urllib3.connectionpool] DEBUG: http://static8.ziroom.com:80 "GET /phoenix/pc/images/price/new-list/377327c0373f87395ab1908cd1607c1b.png HTTP/1.1" 200 3510
2020-04-17 19:14:51 [PIL.PngImagePlugin] DEBUG: STREAM b'IHDR' 16 13
2020-04-17 19:14:51 [PIL.PngImagePlugin] DEBUG: STREAM b'IDAT' 41 3453
2020-04-17 19:14:54 [urllib3.connectionpool] DEBUG: Starting new HTTPS connection (1): aip.baidubce.com:443
2020-04-17 19:14:54 [urllib3.connectionpool] DEBUG: https://aip.baidubce.com:443 "POST /rest/2.0/ocr/v1/general_basic?access_token=24.e97f3cd231bd37ec01f255e525582a21.2592000.1589714081.282335-19383742&aipSdk=python&aipVersion=2_2_18 HTTP/1.1" 200 95
2020-04-17 19:14:54 [scrapy.core.scraper] DEBUG: Scraped from <200 http://www.ziroom.com/z/s100001-p1/>
None
2020-04-17 19:14:54 [urllib3.connectionpool] DEBUG: Starting new HTTP connection (1): static8.ziroom.com:80
2020-04-17 19:14:55 [urllib3.connectionpool] DEBUG: http://static8.ziroom.com:80 "GET /phoenix/pc/images/price/new-list/377327c0373f87395ab1908cd1607c1b.png HTTP/1.1" 200 3510
2020-04-17 19:14:55 [PIL.PngImagePlugin] DEBUG: STREAM b'IHDR' 16 13
2020-04-17 19:14:55 [PIL.PngImagePlugin] DEBUG: STREAM b'IDAT' 41 3453
2020-04-17 19:14:58 [urllib3.connectionpool] DEBUG: Starting new HTTPS connection (1): aip.baidubce.com:443
2020-04-17 19:14:58 [urllib3.connectionpool] DEBUG: https://aip.baidubce.com:443 "POST /rest/2.0/ocr/v1/general_basic?access_token=24.e97f3cd231bd37ec01f255e525582a21.2592000.1589714081.282335-19383742&aipSdk=python&aipVersion=2_2_18 HTTP/1.1" 200 96
2020-04-17 19:14:58 [scrapy.core.scraper] DEBUG: Scraped from <200 http://www.ziroom.com/z/s100001-p1/>
None
2020-04-17 19:14:58 [urllib3.connectionpool] DEBUG: Starting new HTTP connection (1): static8.ziroom.com:80
2020-04-17 19:15:19 [scrapy.core.scraper] ERROR: Spider error processing <GET http://www.ziroom.com/z/s100001-p1/> (referer: None)
Traceback (most recent call last):
  File "C:\Users\rench\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\connection.py", line 157, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "C:\Users\rench\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\util\connection.py", line 84, in create_connection
    raise err
  File "C:\Users\rench\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\util\connection.py", line 74, in create_connection
    sock.connect(sa)
TimeoutError: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\rench\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\connectionpool.py", line 672, in urlopen
    chunked=chunked,
  File "C:\Users\rench\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\connectionpool.py", line 387, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "C:\Users\rench\AppData\Local\Programs\Python\Python37\lib\http\client.py", line 1252, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Users\rench\AppData\Local\Programs\Python\Python37\lib\http\client.py", line 1298, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\Users\rench\AppData\Local\Programs\Python\Python37\lib\http\client.py", line 1247, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Users\rench\AppData\Local\Programs\Python\Python37\lib\http\client.py", line 1026, in _send_output
    self.send(msg)
  File "C:\Users\rench\AppData\Local\Programs\Python\Python37\lib\http\client.py", line 966, in send
    self.connect()
  File "C:\Users\rench\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\connection.py", line 184, in connect
    conn = self._new_conn()
  File "C:\Users\rench\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\connection.py", line 169, in _new_conn
    self, "Failed to establish a new connection: %s" % e
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x000001A24F15F288>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\rench\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\adapters.py", line 449, in send
    timeout=timeout
  File "C:\Users\rench\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\connectionpool.py", line 720, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "C:\Users\rench\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\util\retry.py", line 436, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='static8.ziroom.com', port=80): Max retries exceeded with url: /phoenix/pc/images/price/new-list/377327c0373f87395ab1908cd1607c1b.png (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001A24F15F288>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\rench\AppData\Local\Programs\Python\Python37\lib\site-packages\scrapy\utils\defer.py", line 117, in iter_errback
    yield next(it)
  File "C:\Users\rench\AppData\Local\Programs\Python\Python37\lib\site-packages\scrapy\utils\python.py", line 345, in __next__
    return next(self.data)
  File "C:\Users\rench\AppData\Local\Programs\Python\Python37\lib\site-packages\scrapy\utils\python.py", line 345, in __next__
    return next(self.data)
  File "C:\Users\rench\AppData\Local\Programs\Python\Python37\lib\site-packages\scrapy\core\spidermw.py", line 64, in _evaluate_iterable
    for r in iterable:
  File "C:\Users\rench\AppData\Local\Programs\Python\Python37\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 29, in process_spider_output
    for x in result:
  File "C:\Users\rench\AppData\Local\Programs\Python\Python37\lib\site-packages\scrapy\core\spidermw.py", line 64, in _evaluate_iterable
    for r in iterable:
  File "C:\Users\rench\AppData\Local\Programs\Python\Python37\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 338, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "C:\Users\rench\AppData\Local\Programs\Python\Python37\lib\site-packages\scrapy\core\spidermw.py", line 64, in _evaluate_iterable
    for r in iterable:
  File "C:\Users\rench\AppData\Local\Programs\Python\Python37\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "C:\Users\rench\AppData\Local\Programs\Python\Python37\lib\site-packages\scrapy\core\spidermw.py", line 64, in _evaluate_iterable
    for r in iterable:
  File "C:\Users\rench\AppData\Local\Programs\Python\Python37\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "C:\Users\rench\AppData\Local\Programs\Python\Python37\lib\site-packages\scrapy\core\spidermw.py", line 64, in _evaluate_iterable
    for r in iterable:
  File "D:/python/ziroom/ziroom/spiders/ziroom_spider.py", line 44, in parse
    data['price'] = self._get_price(ret)
  File "D:/python/ziroom/ziroom/spiders/ziroom_spider.py", line 86, in _get_price
    img_ret = requests.get('http:' + url)
  File "C:\Users\rench\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Users\rench\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\rench\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\rench\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\rench\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='static8.ziroom.com', port=80): Max retries exceeded with url: /phoenix/pc/images/price/new-list/377327c0373f87395ab1908cd1607c1b.png (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001A24F15F288>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。'))
2020-04-17 19:15:19 [scrapy.core.engine] INFO: Closing spider (finished)
2020-04-17 19:15:19 [scrapy.statscollectors] INFO: Dumping Scrapy stats:
{'downloader/exception_count': 2,
 'downloader/exception_type_count/twisted.internet.error.ConnectionRefusedError': 2,
 'downloader/request_bytes': 849,
 'downloader/request_count': 4,
 'downloader/request_method_count/GET': 4,
 'downloader/response_bytes': 15599,
 'downloader/response_count': 2,
 'downloader/response_status_count/200': 2,
 'elapsed_time_seconds': 51.599027,
 'finish_reason': 'finished',
 'finish_time': datetime.datetime(2020, 4, 17, 11, 15, 19, 694871),
 'item_scraped_count': 6,
 'log_count/DEBUG': 129,
 'log_count/ERROR': 1,
 'log_count/INFO': 10,
 'log_count/WARNING': 1,
 'response_received_count': 2,
 'retry/count': 2,
 'retry/reason_count/twisted.internet.error.ConnectionRefusedError': 2,
 'robotstxt/request_count': 1,
 'robotstxt/response_count': 1,
 'robotstxt/response_status_count/200': 1,
 'scheduler/dequeued': 3,
 'scheduler/dequeued/memory': 3,
 'scheduler/enqueued': 3,
 'scheduler/enqueued/memory': 3,
 'spider_exceptions/ConnectionError': 1,
 'start_time': datetime.datetime(2020, 4, 17, 11, 14, 28, 95844)}
2020-04-17 19:15:19 [scrapy.core.engine] INFO: Spider closed (finished)
